import pandas as pd
import re
import sys

def main():
    excel_path = r"C:\Users\JinYi\zephyrproject\YTM32B1MC0x_PINMUX_V1.0.xlsx"
    df = pd.read_excel(excel_path, sheet_name="IOMUX")

    port_map = {'PTA': 0, 'PTB': 1, 'PTC': 2, 'PTD': 3, 'PTE': 4}

    output = []
    output.append("/*")
    output.append(" * Auto-generated by script from YTM32B1MC0x_PINMUX_V1.0.xlsx")
    output.append(" * Do not edit manually.")
    output.append(" */")
    output.append("#ifndef ZEPHYR_YTM32_PINCTRL_H_")
    output.append("#define ZEPHYR_YTM32_PINCTRL_H_\n")
    output.append("#define YTM32_PINMUX(port, pin, mux) \\")
    output.append("    ((((port) & 0xF) << 28) | (((pin) & 0x1F) << 24) | (((mux) & 0xF) << 0))\n")

    for index, row in df.iterrows():
        name = str(row['NAME']).strip()
        match = re.match(r'(PT[A-E])_(\d+)', name)
        if not match:
            continue
        port_str = match.group(1)
        pin_num = int(match.group(2))
        port_idx = port_map.get(port_str)
        
        if port_idx is None:
            continue
        
        for alt_idx in range(8):
            alt_col = f"ALT{alt_idx}"
            if alt_col in df.columns:
                val = row[alt_col]
                if pd.isna(val):
                    continue
                val_str = str(val).strip()
                if not val_str:
                    continue
                
                # Clean up the string for macro name (replace invalid chars with _)
                val_clean = re.sub(r'\W+', '_', val_str)
                name_clean = f"{port_str}{pin_num}"

                if val_clean == name:
                    macro_name = f"YTM32_{name_clean}_GPIO"
                else:
                    macro_name = f"YTM32_{name_clean}_{val_clean}"
                    
                macro_value = f"YTM32_PINMUX({port_idx}, {pin_num}, {alt_idx})"
                output.append(f"#define {macro_name:<30} {macro_value}")

    output.append("\n#endif /* ZEPHYR_YTM32_PINCTRL_H_ */")
    
    with open("ytm32b1m-pinctrl.h", "w") as f:
        f.write("\n".join(output))
        f.write("\n")
        
    print(f"Generated {len(output)} lines to ytm32b1m-pinctrl.h")

if __name__ == '__main__':
    main()
