#!/usr/bin/env python3

import argparse
from pathlib import Path
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = {
    "main": "http://schemas.openxmlformats.org/spreadsheetml/2006/main",
    "rel": "http://schemas.openxmlformats.org/officeDocument/2006/relationships",
    "pkgrel": "http://schemas.openxmlformats.org/package/2006/relationships",
}
PORT_MAP = {"PTA": 0, "PTB": 1, "PTC": 2, "PTD": 3, "PTE": 4}
ALT_COLUMNS = [f"ALT{i}" for i in range(8)]


def sanitize(value):
    value = str(value).strip().replace("/", "_")
    value = re.sub(r"[^0-9A-Za-z_]+", "_", value)
    value = re.sub(r"_+", "_", value)
    return value.strip("_")


def column_index(cell_ref):
    match = re.match(r"([A-Z]+)", cell_ref)
    if not match:
        raise ValueError(f"Invalid cell reference: {cell_ref}")
    index = 0
    for char in match.group(1):
        index = index * 26 + ord(char) - ord("A") + 1
    return index - 1


def read_shared_strings(zf):
    if "xl/sharedStrings.xml" not in zf.namelist():
        return []

    root = ET.fromstring(zf.read("xl/sharedStrings.xml"))
    strings = []
    for item in root.findall("main:si", NS):
        strings.append("".join(text.text or "" for text in item.iter(f"{{{NS['main']}}}t")))
    return strings


def workbook_sheets(zf):
    workbook = ET.fromstring(zf.read("xl/workbook.xml"))
    rels = ET.fromstring(zf.read("xl/_rels/workbook.xml.rels"))
    rid_to_target = {rel.attrib["Id"]: rel.attrib["Target"] for rel in rels}

    sheets = {}
    for sheet in workbook.find("main:sheets", NS):
        name = sheet.attrib["name"]
        rid = sheet.attrib[f"{{{NS['rel']}}}id"]
        target = rid_to_target[rid]
        path = target[1:] if target.startswith("/") else f"xl/{target}"
        sheets[name] = path
    return sheets


def cell_value(cell, shared_strings):
    value = cell.find("main:v", NS)
    if value is None:
        inline = cell.find("main:is", NS)
        if inline is None:
            return ""
        return "".join(text.text or "" for text in inline.iter(f"{{{NS['main']}}}t"))

    raw = value.text or ""
    if cell.attrib.get("t") == "s":
        return shared_strings[int(raw)]
    return raw


def read_sheet_rows(excel_path, requested_sheet):
    with zipfile.ZipFile(excel_path) as zf:
        shared_strings = read_shared_strings(zf)
        sheets = workbook_sheets(zf)

        if requested_sheet:
            sheet_name = requested_sheet
        else:
            sheet_name = next((name for name in ("PINMUX", "IOMUX") if name in sheets), None)

        if sheet_name not in sheets:
            raise ValueError(f"Sheet {sheet_name or 'PINMUX/IOMUX'} not found in {excel_path}")

        root = ET.fromstring(zf.read(sheets[sheet_name]))
        parsed_rows = []
        for row in root.findall(".//main:sheetData/main:row", NS):
            values = {}
            for cell in row.findall("main:c", NS):
                values[column_index(cell.attrib["r"])] = cell_value(cell, shared_strings).strip()
            parsed_rows.append(values)

    if not parsed_rows:
        raise ValueError(f"Sheet {sheet_name} is empty")

    header = parsed_rows[0]
    rows = []
    for values in parsed_rows[1:]:
        rows.append({header.get(index, str(index)): value for index, value in values.items()})

    return sheet_name, rows


def generate(excel_path, output_path, sheet_name, source_name, soc_name):
    sheet_name, rows = read_sheet_rows(excel_path, sheet_name)
    guard = "ZEPHYR_DT_BINDINGS_PINCTRL_" + sanitize(Path(output_path).name).upper()

    output = [
        "/*",
        f" * Auto-generated by scripts/generate_pinctrl.py from {source_name}",
        f" * Target: {soc_name}",
        " * Do not edit manually.",
        " */",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#define YTM32_PINMUX(port, pin, mux) \\",
        "\t((((port) & 0xF) << 28) | (((pin) & 0x1F) << 24) | (((mux) & 0xF) << 0))",
        "",
    ]

    seen = {}
    generated = 0

    for row in rows:
        name = row.get("NAME", "").strip()
        match = re.fullmatch(r"(PT[A-E])_(\d+)", name)
        if not match:
            continue

        port_str = match.group(1)
        pin_num = int(match.group(2))
        port_idx = PORT_MAP[port_str]
        name_clean = f"{port_str}{pin_num}"

        for alt_idx, alt_col in enumerate(ALT_COLUMNS):
            val = row.get(alt_col, "").strip()
            if not val:
                continue

            val_clean = sanitize(val)
            if not val_clean:
                continue

            if val_clean == sanitize(name):
                macro_name = f"YTM32_{name_clean}_GPIO"
            else:
                macro_name = f"YTM32_{name_clean}_{val_clean}"

            macro_value = f"YTM32_PINMUX({port_idx}, {pin_num}, {alt_idx})"
            if macro_name in seen and seen[macro_name] != macro_value:
                raise ValueError(f"Duplicate macro {macro_name}: {seen[macro_name]} vs {macro_value}")
            if macro_name in seen:
                continue

            seen[macro_name] = macro_value
            output.append(f"#define {macro_name:<36} {macro_value}")
            generated += 1

    output.extend(["", f"#endif /* {guard} */", ""])
    Path(output_path).write_text("\n".join(output), encoding="utf-8")
    return sheet_name, generated


def main():
    parser = argparse.ArgumentParser(description="Generate YTM32 Zephyr pinctrl macros from a pinmux workbook")
    parser.add_argument("excel", help="Input YTM32 pinmux .xlsx file")
    parser.add_argument("output", help="Output pinctrl header")
    parser.add_argument("--sheet", help="Worksheet name; auto-detects PINMUX then IOMUX when omitted")
    parser.add_argument("--source-name", help="Source name for generated comments")
    parser.add_argument("--soc", default="YTM32", help="Target SoC name for generated comments")
    args = parser.parse_args()

    excel_path = Path(args.excel)
    output_path = Path(args.output)
    source_name = args.source_name or excel_path.name

    sheet_name, generated = generate(excel_path, output_path, args.sheet, source_name, args.soc)
    print(f"Generated {generated} macros from {sheet_name} to {output_path}")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"error: {exc}", file=sys.stderr)
        sys.exit(1)
