/*
 * Copyright (c) 2026 YI JIN <jinyi_2001@foxmail.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * YTM32 ADC Phase 2 extension: DMA continuous sampling.
 *
 * This API supplements the standard Zephyr adc_read() interface for the
 * motor-drive use case where ADC results must be transferred to memory
 * without CPU involvement.  Two trigger modes are offered (see
 * enum adc_ytm32_dma_trigger): a free-running software path and a
 * PWM-synchronised hardware path (eTMR→TMU).
 *
 * Usage:
 *   1. Configure channels with adc_channel_setup() as normal.
 *   2. Allocate a buffer of channel_count * depth * sizeof(uint16_t) bytes.
 *   3. Call adc_ytm32_dma_start() once.
 *   4. The callback fires every 'depth' conversions with a pointer to the
 *      filled buffer.  The callback runs in ISR context and does NOT re-arm
 *      (to avoid ISR starvation in continuous mode).  Call
 *      adc_ytm32_dma_resume() from thread context for the next batch, or
 *      adc_ytm32_dma_stop() to halt.
 *
 * Buffer layout (depth=2, channels={0,2,4}):
 *   [ch0_period0, ch2_period0, ch4_period0,
 *    ch0_period1, ch2_period1, ch4_period1]
 */

#ifndef ZEPHYR_INCLUDE_DRIVERS_ADC_ADC_YTM32_H_
#define ZEPHYR_INCLUDE_DRIVERS_ADC_ADC_YTM32_H_

#include <stdint.h>
#include <zephyr/device.h>

#ifdef __cplusplus
extern "C" {
#endif

/**
 * @brief Callback invoked from DMA ISR after 'depth' PWM periods of data.
 *
 * @param dev      ADC device
 * @param buf      Pointer to the filled sample buffer (same pointer passed
 *                 to adc_ytm32_dma_config.buf)
 * @param ch_count Number of active channels
 * @param depth    Number of complete sequences in the buffer
 * @param user_data Opaque pointer from adc_ytm32_dma_config
 */
typedef void (*adc_ytm32_dma_cb_t)(const struct device *dev,
				   uint16_t *buf,
				   uint8_t ch_count,
				   uint16_t depth,
				   void *user_data);

/**
 * @brief DMA top-half callback invoked before the normal callback.
 *
 * Called from the DMA completion top-half before the normal @p cb.  If the DMA
 * channel is connected as a zero-latency IRQ this runs at NVIC priority 0
 * (never masked by irq_lock/BASEPRI); otherwise it runs in normal DMA ISR
 * context.  In both cases it must NOT use Zephyr kernel APIs (k_sem_give,
 * k_event_post, k_work_submit, etc.).
 *
 * Typical use: read eTMR CNT for latency measurement, run bounded FOC math, or
 * write PWM compare registers.  After this callback the ADC driver pends a
 * normal-priority notification IRQ that invokes @p cb.
 */
typedef void (*adc_ytm32_dma_zl_cb_t)(const struct device *dev,
				      uint16_t *buf,
				      uint8_t ch_count,
				      uint16_t depth,
				      void *user_data);

/**
 * @brief DMA sampling trigger mode.
 */
enum adc_ytm32_dma_trigger {
	/**
	 * Free-running: the ADC self-clocks the sequence back-to-back (software
	 * trigger + continuous conversion).  No eTMR/PWM synchronisation, but
	 * fully working today — use this for general continuous sampling.
	 */
	ADC_YTM32_DMA_TRIGGER_SOFTWARE = 0,
		/**
		 * PWM-synchronised: each board-selected eTMR trigger (INIT_TRIG or
		 * EXT_TRIG) starts one ADC sequence so each DMA sequence is phase-aligned
		 * to the PWM period.
		 *
		 * Verified MD1 recipe (2026-06-06): eTMR0 EXT_TRIG(23) generated by
		 * OTRIG.MIDTEN + MID=MOD/2 (ytmicro,adc-mid-trigger) → TMU route to
		 * ADC0_EXT_TRIG → CIM ADC0_TRIG_SEL=2 (TMU synchronised by ADC functional
		 * clock).  PTU is NOT required (RM §29.4.3.4).
		 *
		 * See trigger_chain.test_stage5_hw_chain for the hardware regression test.
		 */
	ADC_YTM32_DMA_TRIGGER_HARDWARE,
};

/**
 * @brief Configuration for DMA continuous sampling.
 */
struct adc_ytm32_dma_config {
	/** Channel bitmask — same semantics as adc_sequence.channels. */
	uint32_t channels;

	/**
	 * Trigger mode.  Defaults to ADC_YTM32_DMA_TRIGGER_SOFTWARE (0), the
	 * free-running path.  ADC_YTM32_DMA_TRIGGER_HARDWARE is the
	 * PWM-synchronised eTMR→TMU path.
	 */
	enum adc_ytm32_dma_trigger trigger;

	/** ADC resolution: 6, 8, 10, or 12 bits. */
	uint8_t resolution;

	/**
	 * Pre-allocated sample buffer.
	 * Required size: POPCOUNT(channels) * depth * sizeof(uint16_t).
	 */
	uint16_t *buf;

	/**
	 * Number of complete ADC sequences (PWM periods) per callback.
	 * Higher values reduce callback rate but increase latency.
	 */
	uint16_t depth;

	/**
	 * DMA top-half callback (optional).  Called before @p cb and must be safe for
	 * zero-latency context: no Zephyr kernel APIs.  Set to NULL to skip.
	 */
	adc_ytm32_dma_zl_cb_t zl_cb;

	/**
	 * Normal callback invoked after 'depth' sequences from the ADC driver's
	 * software-pended notification ISR.  This callback may use ISR-safe Zephyr
	 * APIs such as k_sem_give().  At least one of @p cb and @p zl_cb must be
	 * non-NULL.
	 */
	adc_ytm32_dma_cb_t cb;

	/** Opaque pointer forwarded to both @p zl_cb and @p cb. */
	void *user_data;
};

/** Runtime timing values captured after the ADC clock has been initialized. */
struct adc_ytm32_timing {
	uint32_t fadc_hz;
	uint8_t sample_time;
	uint32_t sample_ns;
	uint32_t conversion_ns;
	uint32_t startup_ns;
};

/**
 * @brief Start DMA continuous sampling.
 *
 * Arms the DMA channel to drain the ADC FIFO into buf on every sequence
 * completion; the callback fires once per 'depth' sequences.  The DMA top-half
 * stops the channel before invoking callbacks; call adc_ytm32_dma_resume() from
 * thread context to collect the next batch.
 *
 * Trigger mode (cfg->trigger):
 * - ADC_YTM32_DMA_TRIGGER_SOFTWARE (default): the ADC free-runs in continuous
 *   conversion mode.  Working path; no eTMR/PWM dependency.
 * - ADC_YTM32_DMA_TRIGGER_HARDWARE: PWM-synchronised via eTMR→TMU.  Requires
 *   ytmicro,hw-trigger-source + ytmicro,tmu in DTS and a running eTMR with the
 *   board-selected trigger source enabled (INIT_TRIG or EXT_TRIG).
 *
 * The calling code is responsible for ensuring:
 * - adc_channel_setup() has been called for every channel in cfg->channels.
 * - (hardware mode only) eTMR is configured and running with the trigger source
 *   selected by the ADC node's ytmicro,hw-trigger-source property.
 *
 * @note Errata E600001: the hardware-trigger period MUST stay below 5 ms.  The
 *       motor-drive use case (PWM trigger every ~50 µs) satisfies this, and
 *       continuous (LOOP) sampling at that rate is unaffected by the errata.
 *       For trigger periods above 5 ms the first channel of each sequence would
 *       read an inaccurate value; the errata's workaround there is to convert
 *       the first channel twice and discard the first result (reducing the
 *       usable channel count to 7).  That slow-trigger workaround is NOT
 *       implemented here because it is not needed for motor drive.
 *
 * @param dev ADC device (e.g. DEVICE_DT_GET(DT_NODELABEL(adc0)))
 * @param cfg DMA sampling configuration
 * @return 0 on success, negative errno on failure
 */
int adc_ytm32_dma_start(const struct device *dev,
			const struct adc_ytm32_dma_config *cfg);

/**
 * @brief Stop hardware-triggered DMA sampling.
 *
 * Stops the ADC and DMA channel.  Safe to call from any context.
 *
 * @param dev ADC device
 * @return 0 on success, negative errno on failure
 */
int adc_ytm32_dma_stop(const struct device *dev);

/**
 * @brief Re-arm DMA for the next batch (thread context only).
 *
 * After the DMA callback fires (in ISR context), call this from thread
 * context to prepare the DMA/ADC for the next sampling batch.  Stops the
 * ADC briefly, re-arms DMA, and restarts the ADC.
 *
 * @param dev ADC device
 * @return 0 on success, negative errno on failure
 */
int adc_ytm32_dma_resume(const struct device *dev);

/** Read the configured FADC timing for diagnostics and calibration reports. */
int adc_ytm32_get_timing(const struct device *dev, uint8_t sample_time,
				 struct adc_ytm32_timing *out);

/** Read the ADC0 CIM trigger selector programmed by the driver. */
int adc_ytm32_get_cim_trigger_select(const struct device *dev,
					     uint32_t *select);

#ifdef __cplusplus
}
#endif

#endif /* ZEPHYR_INCLUDE_DRIVERS_ADC_ADC_YTM32_H_ */
